### ISSUE TITLE
Hide From Groups Not Working Well

### ISSUE THREAD

**Issue by VSEphpbb** [phpbb-extensions/ad-management#102]
https://www.phpbb.com/customise/db/extension/ads/support/topic/183071

If you Hide ads from Regsistered users, but not a special group (like Newly Registered Users), the special group still won't see the ads because they are members of both registered and newly registered users.

**Comment by senky** [comment]
How do you propose to solve this? If we only hide ads when user is member of groups that all have ad hiding enabled, it won't work in situations when admin creates "donors" group which members are not supposed to see the ads...

**Comment by VSEphpbb** [comment]
If you read the topic, I basically said to the user that they're just using the extension wrong...trying to make it do something it's not intended to do.

This option is too wide spread to be used so specifically.
