### ISSUE TITLE
Hide UCP module for members without ads

### ISSUE THREAD

**Issue by senky** [phpbb-extensions/ad-management#103]
Just thinking out loud... Maybe there is a way to dynamically set `u_` permission? That way we could set module auth to `ext_phpbb/ads && u_ads`. And set `u_ads` to true when user has at least one ad assigned.

**Comment by VSEphpbb** [comment]
There is. Create a user permission for viewing that module. Then set it to true when an ad is assigned to a user, and back to false when that ad is deleted or the user removed from that ad as an owner.

**Comment by VSEphpbb** [comment]
Something like this maybe
```php
acl_set('user', 0, $user_id, array('u_ads' => true/false))
```
