### ISSUE TITLE
Adblock Plus hides enable radio button for Ad blocker friendly message

### ISSUE THREAD

**Issue by Derky** [phpbb-extensions/ad-management#36]
When using Adblock Plus in Chrome the enable radio button is hidden:
![screenshot](https://user-images.githubusercontent.com/318762/27380547-d0fe1a16-567f-11e7-9fdd-51a55e594c85.png)

Removing `id="adblocker_message"` makes it visible again.

In Adblock Plus I'm also subscribed to the additional filter list "Adblock warning deleted list", that's the first option below "Other filters" on the Adblock Filters page.

**Comment by VSEphpbb** [comment]
Lol... The use of "ad" is so toxic when an ad blocker is installed.

I would just rename this item "blocker_message"

**Comment by senky** [comment]
@VSEphpbb taking psychology into consideration, I would like to keep "friendly" instead of some negative word..

**Comment by VSEphpbb** [comment]
But it's not really 'friendly" :). That it's encased in a red alert bubble that will always be present to the user so long as they have ad blocks enabled, at it's most basic it's a message, but to use an adjective of that its more of a persistent alert or warning IMO. 

`"Ad blocker detected message"` is better and not negative.
