### ISSUE TITLE
RAND() + ad_priority can be further perfected

### ISSUE THREAD

**Issue by senky** [phpbb-extensions/ad-management#39]
`ORDER BY -LOG(RAND()) / ad_priority` will yield better distribution. See:

https://stackoverflow.com/a/12301949/2908600

**Comment by VSEphpbb** [comment]
No LOG() for SQlite

**Comment by senky** [comment]
True, but it is present everywhere else. So I assume we could implement this and display a note for users with SQLite, that their distribution will be less even.

**Comment by VSEphpbb** [comment]
No note would be necessary IMO. Even without this I ran some tests and the distribution seems good enough to not be a concern.

**Comment by VSEphpbb** [comment]
[08:01:21]  <VSE>	By the way -LOG(RAND()) / ad_priority is not as good
[08:01:44]  <VSE>	With ads set to 1,2,10 the distribution is even between all 3... the 10 his not more heavily weighted
[08:01:53]  <VSE>	3,33,64
The order is also reversed, giving the reverse priority weight:
1: 64 hits
2: 33 hits
10: 3 hits
