### ISSUE TITLE
Flex box has undesired results with some text

### ISSUE THREAD

**Issue by VSEphpbb** [phpbb-extensions/ad-management#7]
The flex-box styling is great but it seems to have undesirable effects on plain text. For example the following code:
```html
Hosting provided by <a href="http://foobar">FooBar Hosting</a>
```
There is no space in between the text and the anchor:
```
Hosting provided byFooBar Hosting
```

**Comment by VSEphpbb** [comment]
An initial solution is to wrap the ad code in this example in a div tag but if there's a wau to tweak our CSS to address this that would be ideal.

**Comment by senky** [comment]
We will see: https://stackoverflow.com/q/44432447/2908600

**Comment by VSEphpbb** [comment]
@senky We could just pre-wrap all ad-codes in a DIV...

```html
<div class="phpbb-admanagement-center"><div>{{ AD_BELOW_FOOTER }}</div></div>

```
